name: Build LaTeX script
on:
  push:
    paths:
      - 'Script/**'
      - 'Beispiele/**'
  pull_request:
    paths:
      - 'Script/**'
      - 'Beispiele/**'
      - '.github/workflows/**'
  workflow_dispatch:

# Cancel running jobs on force-push
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Compile script
        uses: xu-cheng/texlive-action@v2
        with:
          scheme: full
          run: |
            cd Script
            apk add make
            make
            make
            mv main.pdf script_programmieren.pdf

      - name: Upload PDF as artifact
        uses: actions/upload-artifact@v4
        with:
          name: script_programmieren
          path: |
            Script/script_programmieren.pdf
